# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.10-strech
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            brew install hadolint
            chmod +x /bin/hadolint
            
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
workflows:
  build-workflow:
    jobs:
      - build